### ISSUE TITLE
Skrive funksjonsbeskrivelse til Evry ang tilgang i folkereg  

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/louie#1]
https://rom.t-fk.no/sites/Prosjektveiviseren/tfkvarsel/_layouts/15/start.aspx#/Lists/Oppgaver/DispForm.aspx?ID=68&Source=https%3A%2F%2From%2Et%2Dfk%2Eno%2Fsites%2FProsjektveiviseren%2Ftfkvarsel%2FSitePages%2FForside%2Easpx&ContentTypeId=0x010800233B015F95174C9A8EB505493841DE8D2800E50E7084383C904CA5F3784ABD561229

**Comment by maccyber** [comment]
Har undertegnet og sendt
